### 4.2 Modeling/4.3 Feature selection

In [45]:
# Customized the train_test_split for augmentated dataset

In [46]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

def balanced_group_train_test_split(X, y, group_col='augmented_from_uniprot_id', 
                                   test_size=0.2, random_state=None):
    """
    Splits data into balanced train/test sets while keeping augmented groups together.
    
    Parameters:
    X (pd.DataFrame): Feature dataframe containing the group column
    y (pd.Series): Target labels
    group_col (str): Name of the column containing group IDs
    test_size (float): Proportion of data for testing (default 0.2)
    random_state (int): Random seed for reproducibility
    
    Returns:
    (pd.DataFrame, pd.DataFrame, pd.Series, pd.Series): X_train, X_test, y_train, y_test
    """
    # Validate inputs
    if group_col not in X.columns:
        raise ValueError(f"Group column '{group_col}' not found in feature dataframe")
        
    if len(X) != len(y):
        raise ValueError("X and y must have the same number of samples")

    rng = np.random.RandomState(random_state)
    combined = X.copy()
    combined['_label'] = y.values

    # Create group metadata
    group_meta = combined.groupby(group_col).agg({
        '_label': 'first',
        group_col: 'count'
    }).rename(columns={group_col: 'count'}).reset_index()

    train_groups, test_groups = [], []

    # Stratified group splitting
    for label in group_meta['_label'].unique():
        label_groups = group_meta[group_meta['_label'] == label]
        total_samples = label_groups['count'].sum()
        test_samples_target = int(total_samples * test_size)
        
        label_groups = shuffle(label_groups, random_state=rng)
        
        # Select groups for test set
        cumulative, selected = 0, []
        for _, row in label_groups.iterrows():
            if cumulative >= test_samples_target:
                break
            selected.append(row[group_col])
            cumulative += row['count']
        
        # Assign remaining groups to train
        remaining = list(set(label_groups[group_col]) - set(selected))
        test_groups.extend(selected)
        train_groups.extend(remaining)

    # Create splits
    train_mask = combined[group_col].isin(train_groups)
    test_mask = combined[group_col].isin(test_groups)
    
    # Return splits with group column removed from features
    return (
            X[train_mask].drop(columns=[group_col]),
            X[test_mask].drop(columns=[group_col]),
            y[train_mask],
            y[test_mask])

    # return (
    #         X[train_mask],
    #         X[test_mask],
    #         y[train_mask],
    #         y[test_mask])

In [47]:
df = pd.read_pickle("final_dataset_with_all_new.pkl")

y = df["label"]
target = "label"
features = list(df.columns)

features.remove(target)

# Select all columns starting with 'onehot' for features
x = df[features]

# Split data into train and test sets
x_train, x_test, y_train, y_test = balanced_group_train_test_split(
    x,
    y,
    group_col='augmentated from uniprot ID',
    test_size=0.2,
    random_state=42
)

In [48]:
# training_uniprot = set(x_train["augmentated from uniprot ID"])
# testing_uniprot = set(x_test["augmentated from uniprot ID"])
# # Find any overlapping UniProt IDs
# overlap = training_uniprot.intersection(testing_uniprot)

# # Check if there's any overlap
# if len(overlap) > 0:
#     print(f"Found {len(overlap)} overlapping UniProt IDs between training and test sets")
#     print("First few overlapping IDs:", list(overlap)[:5])
# else:
#     print("No overlap found between training and test sets - good to proceed!")

task 36: modeling direct from only PLM embedding, we first compare using embeddings from either ESM2 or PTM-mamba to represent the whole protein or the residue embeddings,

In [49]:
import pandas as pd
import pickle
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

def make_pipeline(classifier):
    """Creates a machine learning pipeline with a Random Forest Classifier.

    Returns:
        Pipeline: A scikit-learn pipeline with a RandomForestClassifier as the final step.
    """
    steps = [("classifier", classifier)]
    pipe = Pipeline(steps)
    return pipe

def train(df, classifier):
    """Trains a Random Forest model using the specified DataFrame.

    Parameters:
        df (pd.DataFrame): The DataFrame containing the features and target variable.

    Returns:
        Pipeline: The trained RandomForest model pipeline.
    """
    # We are predicting the protein labels
    y = df["label"]
    target = "label"
    features = list(df.columns)
    
    features.remove(target)

    # Select all columns starting with 'onehot' for features
    x = df[features]

    # Split data into train and test sets
    x_train, x_test, y_train, y_test = balanced_group_train_test_split(
        x,
        y,
        group_col='augmentated from uniprot ID',
        test_size=0.2,
        random_state=42
    )

    # Count positive and negative labels in y_train and y_test
    y_train_counts = y_train.value_counts()
    y_test_counts = y_test.value_counts()

    print("Label counts in y_train:")
    print(y_train_counts)

    print("\nLabel counts in y_test:")
    print(y_test_counts)

    trained_model = make_pipeline(classifier)
    trained_model.fit(x_train, y_train)

    # Make predictions
    y_train_pred = trained_model.predict(x_train)
    y_test_pred = trained_model.predict(x_test)

    # Calculate model metrics
    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)
    train_report = classification_report(y_train, y_train_pred, zero_division=1)
    test_report = classification_report(y_test, y_test_pred, zero_division=1)

    # Print metrics in a readable format
    print(f"Model {classifier} Performance Metrics:\n")

    print("Training Data Metrics:")
    print(f"Accuracy: {train_accuracy:.2f}")
    print("Classification Report:")
    print(train_report)  # This prints the report as a table

    print("\nTest Data Metrics:")
    print(f"Accuracy: {test_accuracy:.2f}")
    print("Classification Report:")
    print(test_report)  # This prints the report as a table

    print("Successfully trained the model.")
    return trained_model

In [50]:
training_dataset_df = pd.read_pickle("final_dataset_with_all_new.pkl")
training_dataset_df = training_dataset_df[training_dataset_df["usage"] == "training"]

In [51]:
training_dataset_df.head(5)

,Unnamed: 0,uniprot_id,sequence,site,label,augmentated from uniprot ID,human Site and Mutation,usage,unique_id,deephase_phys_multi,...,ptmmamba_residue_embedding_759,ptmmamba_residue_embedding_760,ptmmamba_residue_embedding_761,ptmmamba_residue_embedding_762,ptmmamba_residue_embedding_763,ptmmamba_residue_embedding_764,ptmmamba_residue_embedding_765,ptmmamba_residue_embedding_766,ptmmamba_residue_embedding_767,phospho_score
0,0,H7C5C7,XVAQQEQELDIKKNERLWLLDDSKSWWRVRNSMNKTGFVPSNYVER...,73,1,P16333,S73s,training,H7C5C7_73_XVAQQEQELDIKKNERLWLLDDSKSWWRVRNSMNKT...,0.203,...,-0.930157,-0.784488,1.378070,1.125187,-0.962103,0.749272,-0.813084,0.488083,1.446624,0.526
1,1,A0A5F9CW23,MAEEVVVVAKFDYVAQQEQELDIKKNERLWLLDDSKSWWRVRNSMN...,85,1,P16333,S85s,training,A0A5F9CW23_85_MAEEVVVVAKFDYVAQQEQELDIKKNERLWLL...,0.185,...,-0.833150,-0.543848,1.270835,1.192153,-0.817320,0.709415,-1.378276,0.626975,2.133350,0.579
2,2,Q5RF68,MDWLNVFKDFFSIGKVKRKPsVPDSASPADDSFVDPGERLYDLNMP...,21,1,P16333,S21s,training,Q5RF68_21_MDWLNVFKDFFSIGKVKRKPsVPDSASPADDSFVDP...,0.096,...,-1.474621,-0.104392,1.062815,0.442375,-0.308503,-0.050680,-1.171706,1.861005,0.189925,0.571
3,3,H3A391,MTEEVTVIAKFDYVAQQEQELDIKKNEKLLLLDDSKSWWRVRNSMN...,85,1,P16333,S85s,training,H3A391_85_MTEEVTVIAKFDYVAQQEQELDIKKNEKLLLLDDSK...,0.108,...,-0.708835,-0.368524,0.630111,0.287115,0.439652,0.259266,-1.870489,2.179887,0.830376,0.379
4,4,A0A8J1IQP6,MSLNGRRGSGRPGYYYRLIGRSQLQRQRSRSRSRNRPARRESPPER...,725,1,Q5VWQ8,S725s,training,A0A8J1IQP6_725_MSLNGRRGSGRPGYYYRLIGRSQLQRQRSRS...,0.282,...,-0.940106,-0.094523,0.474609,-0.267281,-0.266375,0.243640,-0.773728,1.224039,-0.136662,0.374

In [52]:
columns = training_dataset_df.columns
columns

Index(['Unnamed: 0', 'uniprot_id', 'sequence', 'site', 'label',
       'augmentated from uniprot ID', 'human Site and Mutation', 'usage',
       'unique_id', 'deephase_phys_multi',
       ...
       'ptmmamba_residue_embedding_759', 'ptmmamba_residue_embedding_760',
       'ptmmamba_residue_embedding_761', 'ptmmamba_residue_embedding_762',
       'ptmmamba_residue_embedding_763', 'ptmmamba_residue_embedding_764',
       'ptmmamba_residue_embedding_765', 'ptmmamba_residue_embedding_766',
       'ptmmamba_residue_embedding_767', 'phospho_score'],
      dtype='object', length=4454)

In [53]:
always_exclude_columns = ['Unnamed: 0', 'uniprot_id', 'sequence', 'site',  'human Site and Mutation', 'usage',
       'unique_id', "anchor_score"]

In [54]:
esm_training_dataset_df = training_dataset_df.filter(regex=r'^(esm_protein_embedding_|esm_residue_embedding_|label|augmentated from uniprot ID)')
ptmmamba_training_dataset_df = training_dataset_df.filter(regex=r'^(ptmmamba_residue_embedding|ptmmamba_protein_embedding_position|label|augmentated from uniprot ID)')

In [55]:
esm_training_dataset_df.head(5)

,label,augmentated from uniprot ID,esm_protein_embedding_0,esm_protein_embedding_1,esm_protein_embedding_2,esm_protein_embedding_3,esm_protein_embedding_4,esm_protein_embedding_5,esm_protein_embedding_6,esm_protein_embedding_7,...,esm_residue_embedding_1270,esm_residue_embedding_1271,esm_residue_embedding_1272,esm_residue_embedding_1273,esm_residue_embedding_1274,esm_residue_embedding_1275,esm_residue_embedding_1276,esm_residue_embedding_1277,esm_residue_embedding_1278,esm_residue_embedding_1279
0,1,P16333,0.021365,-0.020171,0.021621,0.095043,-0.057202,-0.050794,0.071949,0.006663,...,0.156998,-0.048794,-0.288164,-0.169802,-0.087454,-0.099428,-0.027398,-0.170118,-0.108479,-0.087466
1,1,P16333,0.024337,-0.044602,0.026486,0.129851,-0.089049,-0.042135,0.083374,0.002857,...,0.155553,-0.035488,-0.296511,-0.183268,-0.062212,-0.104337,-0.041655,-0.249533,-0.119220,-0.131040
2,1,P16333,0.019708,-0.037163,0.012426,0.091465,-0.085954,-0.071278,0.061197,0.026536,...,0.057347,-0.025978,-0.107604,-0.075288,-0.089051,-0.013340,0.077709,-0.006540,-0.176868,-0.109933
3,1,P16333,0.016691,-0.067765,-0.026445,0.096103,-0.135539,-0.088490,0.060594,-0.063513,...,0.172102,-0.006700,-0.067678,-0.127333,-0.010801,-0.093588,-0.160996,-0.111260,-0.075962,-0.120771
4,1,Q5VWQ8,0.028754,-0.000879,0.022422,0.037734,-0.101758,-0.097661,0.048510,0.022037,...,0.104533,0.161240,-0.105866,-0.053904,-0.058608,-0.270229,-0.001867,0.031717,-0.097747,-0.078485

In [56]:
ptmmamba_training_dataset_df.head(5)

,label,augmentated from uniprot ID,ptmmamba_protein_embedding_position_0,ptmmamba_protein_embedding_position_1,ptmmamba_protein_embedding_position_2,ptmmamba_protein_embedding_position_3,ptmmamba_protein_embedding_position_4,ptmmamba_protein_embedding_position_5,ptmmamba_protein_embedding_position_6,ptmmamba_protein_embedding_position_7,...,ptmmamba_residue_embedding_758,ptmmamba_residue_embedding_759,ptmmamba_residue_embedding_760,ptmmamba_residue_embedding_761,ptmmamba_residue_embedding_762,ptmmamba_residue_embedding_763,ptmmamba_residue_embedding_764,ptmmamba_residue_embedding_765,ptmmamba_residue_embedding_766,ptmmamba_residue_embedding_767
0,1,P16333,0.306219,0.075793,0.279163,0.129615,-0.124552,0.055463,-0.138853,-0.701024,...,0.905219,-0.930157,-0.784488,1.378070,1.125187,-0.962103,0.749272,-0.813084,0.488083,1.446624
1,1,P16333,0.164579,-0.161845,0.364336,0.196843,-0.142813,-0.032246,-0.274839,-0.841149,...,1.007017,-0.833150,-0.543848,1.270835,1.192153,-0.817320,0.709415,-1.378276,0.626975,2.133350
2,1,P16333,0.119370,-0.170645,0.069318,0.130563,0.066603,-0.061079,0.007130,-0.659120,...,0.972614,-1.474621,-0.104392,1.062815,0.442375,-0.308503,-0.050680,-1.171706,1.861005,0.189925
3,1,P16333,0.252884,-0.104365,0.170443,0.096454,0.100202,-0.116983,-0.210762,-0.806122,...,0.809762,-0.708835,-0.368524,0.630111,0.287115,0.439652,0.259266,-1.870489,2.179887,0.830376
4,1,Q5VWQ8,0.218763,0.069228,0.227428,0.684456,0.372327,-0.193287,-0.635183,-0.696890,...,0.046559,-0.940106,-0.094523,0.474609,-0.267281,-0.266375,0.243640,-0.773728,1.224039,-0.136662

In [57]:
plm_feature_df_lst = [esm_training_dataset_df, ptmmamba_training_dataset_df]
plm_name_lst = ["esm", "ptmmamba"]

In [58]:
for name, loaded_df in zip(plm_name_lst, plm_feature_df_lst):
    print(f"Modeling using {name}")
    model = train(loaded_df, RandomForestClassifier(max_depth=7))

Modeling using esm
Label counts in y_train:
label
0    966
1    841
Name: count, dtype: int64

Label counts in y_test:
label
0    233
1    226
Name: count, dtype: int64
Model RandomForestClassifier(max_depth=7) Performance Metrics:

Training Data Metrics:
Accuracy: 0.97
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.97      0.97       966
           1       0.96      0.97      0.96       841

    accuracy                           0.97      1807
   macro avg       0.97      0.97      0.97      1807
weighted avg       0.97      0.97      0.97      1807


Test Data Metrics:
Accuracy: 0.79
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.93      0.82       233
           1       0.90      0.64      0.75       226

    accuracy                           0.79       459
   macro avg       0.81      0.78      0.78       459
weighted avg       0.81      0.79      0.78       459

Successfully trained the model.
Modeling using ptmmamba
Label counts in y_train:
label
0    966
1    841
Name: count, dtype: int64

Label counts in y_test:
label
0    233
1    226
Name: count, dtype: int64
Model RandomForestClassifier(max_depth=7) Performance Metrics:

Training Data Metrics:
Accuracy: 0.99
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.98      0.99      0.99       841

    accuracy                           0.99      1807
   macro avg       0.99      0.99      0.99      1807
weighted avg       0.99      0.99      0.99      1807


Test Data Metrics:
Accuracy: 0.75
Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.83      0.77       233
           1       0.79      0.66      0.72       226

    accuracy                           0.75       459
   macro avg       0.75      0.75      0.74       459
weighted avg       0.75      0.75      0.75       459

Successfully trained the model.

In [59]:
import gc
gc.collect()

1221

task 37: Then we tested modeling from multi-scale biology features plus onehot encoding for the -7 to +7 motif, the result show that multi-scale biology features also can be used to predict the 14-3-3 binding when compare with only use onehot encoded motif feature.

In [60]:
# we first test to only use onehot encoding for the prediction

In [61]:
onehot_training_dataset_df = training_dataset_df.filter(regex=r'^(onehot_|label|augmentated from uniprot ID)')
onehot_training_dataset_df

,label,augmentated from uniprot ID,onehot_-7_A,onehot_-7_C,onehot_-7_D,onehot_-7_E,onehot_-7_F,onehot_-7_G,onehot_-7_H,onehot_-7_I,...,onehot_7_P,onehot_7_Q,onehot_7_R,onehot_7_S,onehot_7_T,onehot_7_V,onehot_7_W,onehot_7_Y,onehot_7_s,onehot_7_t
0,1,P16333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,P16333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,P16333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,P16333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,Q5VWQ8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,0,O15417,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2262,0,Q9BYW2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2263,0,Q8N3K9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2264,0,Q6ZRS2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2265,0,Q12955,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
print(f"Modeling only use onehot encoding features")
model = train(onehot_training_dataset_df, RandomForestClassifier(max_depth=7))

Modeling only use onehot encoding features
Label counts in y_train:
label
0    966
1    841
Name: count, dtype: int64

Label counts in y_test:
label
0    233
1    226
Name: count, dtype: int64
Model RandomForestClassifier(max_depth=7) Performance Metrics:

Training Data Metrics:
Accuracy: 0.90
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.92      0.91       966
           1       0.90      0.89      0.90       841

    accuracy                           0.90      1807
   macro avg       0.90      0.90      0.90      1807
weighted avg       0.90      0.90      0.90      1807


Test Data Metrics:
Accuracy: 0.83
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       233
           1       0.85      0.80      0.82       226

    accuracy                           0.83       459
   macro avg       0.83      0.83      0.83       459
weighted avg       0.83      0.83      0.83       459

Successfully trained the model.

In [63]:
# then we test use both onehot encode and biological features

In [64]:
excluded_prefixes = (
    'esm_protein_embedding_',
    'esm_residue_embedding_',
    'ptmmamba_residue_embedding_',
    'ptmmamba_protein_embedding_'
)

# Create a list of columns to keep (those that don't start with excluded prefixes)
columns_to_keep = [col for col in training_dataset_df.columns if not any(col.startswith(prefix) for prefix in excluded_prefixes)]
columns_to_keep = [col for col in columns_to_keep if col not in always_exclude_columns]
# Now select those columns from your DataFrame
biology_training_dataset_df = training_dataset_df[columns_to_keep]

In [65]:
biology_training_dataset_df

,label,augmentated from uniprot ID,deephase_phys_multi,deephase_w2v_multi,deephase_score,iupred_score,onehot_-7_A,onehot_-7_C,onehot_-7_D,onehot_-7_E,...,SCD,kappa,FCR,NCPR,fK,fR,fE,fD,faro,phospho_score
0,1,P16333,0.203,0.160,0.182,0.541878,0.0,0.0,0.0,0.0,...,-0.950,0.363,0.385,-0.077,0.077,0.077,0.000,0.154,0.000,0.526
1,1,P16333,0.185,0.173,0.179,0.509769,0.0,0.0,0.0,0.0,...,-0.546,-1.000,0.600,0.200,0.200,0.200,0.000,0.000,0.000,0.579
2,1,P16333,0.096,0.129,0.113,0.465241,0.0,0.0,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.571
3,1,P16333,0.108,0.352,0.230,0.566480,0.0,0.0,0.0,0.0,...,-0.946,0.250,0.381,-0.095,0.048,0.095,0.000,0.190,0.000,0.379
4,1,Q5VWQ8,0.282,0.742,0.512,0.837511,0.0,0.0,0.0,0.0,...,-0.158,0.382,0.231,-0.077,0.038,0.038,0.077,0.038,0.038,0.374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,0,O15417,0.329,0.774,0.552,0.798249,0.0,0.0,0.0,0.0,...,14.619,0.152,0.278,-0.160,0.024,0.036,0.154,0.059,0.018,0.080
2262,0,Q9BYW2,0.283,0.776,0.530,0.831250,0.0,0.0,0.0,0.0,...,22.077,0.190,0.389,-0.246,0.063,0.008,0.214,0.095,0.000,0.274
2263,0,Q8N3K9,0.203,0.726,0.464,0.566480,0.0,0.0,0.0,0.0,...,9.433,0.217,0.229,-0.178,0.034,0.000,0.178,0.025,0.059,0.063
2264,0,Q6ZRS2,0.411,0.762,0.587,0.930790,0.0,0.0,0.0,0.0,...,0.416,0.164,0.080,0.034,0.017,0.040,0.011,0.006,0.011,0.155
2265,0,Q12955,0.275,0.749,0.512,0.915074,0.0,0.0,0.0,1.0,...,3.815,0.112,0.268,-0.061,0.068,0.035,0.090,0.071,0.039,0.118

In [66]:
print(f"Modeling using multi-scale biology features")
model = train(biology_training_dataset_df, RandomForestClassifier(max_depth=7))

Modeling using multi-scale biology features
Label counts in y_train:
label
0    966
1    841
Name: count, dtype: int64

Label counts in y_test:
label
0    233
1    226
Name: count, dtype: int64
Model RandomForestClassifier(max_depth=7) Performance Metrics:

Training Data Metrics:
Accuracy: 0.90
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       966
           1       0.89      0.89      0.89       841

    accuracy                           0.90      1807
   macro avg       0.90      0.90      0.90      1807
weighted avg       0.90      0.90      0.90      1807


Test Data Metrics:
Accuracy: 0.83
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.87      0.84       233
           1       0.85      0.80      0.83       226

    accuracy                           0.83       459
   macro avg       0.84      0.83      0.83       459
weighted avg       0.84      0.83      0.83       459

Successfully trained the model.

In [67]:
import gc
gc.collect()

75

task 38: We then test using both PLM and biology features, the results show that using both PLM and biology features shows improved results compared with using only PLM or multi-scale biology features.

In [70]:
columns_to_keep = [col for col in training_dataset_df.columns if col not in always_exclude_columns]
training_dataset_df[columns_to_keep]

,label,augmentated from uniprot ID,deephase_phys_multi,deephase_w2v_multi,deephase_score,iupred_score,onehot_-7_A,onehot_-7_C,onehot_-7_D,onehot_-7_E,...,ptmmamba_residue_embedding_759,ptmmamba_residue_embedding_760,ptmmamba_residue_embedding_761,ptmmamba_residue_embedding_762,ptmmamba_residue_embedding_763,ptmmamba_residue_embedding_764,ptmmamba_residue_embedding_765,ptmmamba_residue_embedding_766,ptmmamba_residue_embedding_767,phospho_score
0,1,P16333,0.203,0.160,0.182,0.541878,0.0,0.0,0.0,0.0,...,-0.930157,-0.784488,1.378070,1.125187,-0.962103,0.749272,-0.813084,0.488083,1.446624,0.526
1,1,P16333,0.185,0.173,0.179,0.509769,0.0,0.0,0.0,0.0,...,-0.833150,-0.543848,1.270835,1.192153,-0.817320,0.709415,-1.378276,0.626975,2.133350,0.579
2,1,P16333,0.096,0.129,0.113,0.465241,0.0,0.0,0.0,0.0,...,-1.474621,-0.104392,1.062815,0.442375,-0.308503,-0.050680,-1.171706,1.861005,0.189925,0.571
3,1,P16333,0.108,0.352,0.230,0.566480,0.0,0.0,0.0,0.0,...,-0.708835,-0.368524,0.630111,0.287115,0.439652,0.259266,-1.870489,2.179887,0.830376,0.379
4,1,Q5VWQ8,0.282,0.742,0.512,0.837511,0.0,0.0,0.0,0.0,...,-0.940106,-0.094523,0.474609,-0.267281,-0.266375,0.243640,-0.773728,1.224039,-0.136662,0.374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,0,O15417,0.329,0.774,0.552,0.798249,0.0,0.0,0.0,0.0,...,-1.177676,-0.877304,0.674698,-0.195342,0.283925,0.078973,0.930381,0.637896,-0.366109,0.080
2262,0,Q9BYW2,0.283,0.776,0.530,0.831250,0.0,0.0,0.0,0.0,...,-1.549038,-0.295345,-0.262526,-0.634858,-0.357382,0.593850,-0.580129,0.019379,-0.784574,0.274
2263,0,Q8N3K9,0.203,0.726,0.464,0.566480,0.0,0.0,0.0,0.0,...,-0.909634,-0.845351,-0.325931,-0.011938,-0.855250,-0.535025,0.514734,0.020328,-0.189157,0.063
2264,0,Q6ZRS2,0.411,0.762,0.587,0.930790,0.0,0.0,0.0,0.0,...,-1.190711,0.183619,1.008728,-0.325716,-1.453191,-0.757268,-0.204297,0.862000,-1.027532,0.155
2265,0,Q12955,0.275,0.749,0.512,0.915074,0.0,0.0,0.0,1.0,...,-0.947864,0.082668,-0.058106,-1.147494,-0.545297,-0.056368,-0.360111,0.239430,-1.013324,0.118

In [71]:
print(f"Modeling using both PLM and biology features")
model = train(training_dataset_df[columns_to_keep], RandomForestClassifier(max_depth=7))

Modeling using both PLM and biology features
Label counts in y_train:
label
0    966
1    841
Name: count, dtype: int64

Label counts in y_test:
label
0    233
1    226
Name: count, dtype: int64
Model RandomForestClassifier(max_depth=7) Performance Metrics:

Training Data Metrics:
Accuracy: 0.97
Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.97      0.97       966
           1       0.96      0.98      0.97       841

    accuracy                           0.97      1807
   macro avg       0.97      0.97      0.97      1807
weighted avg       0.97      0.97      0.97      1807


Test Data Metrics:
Accuracy: 0.79
Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.93      0.82       233
           1       0.90      0.65      0.76       226

    accuracy                           0.79       459
   macro avg       0.82      0.79      0.79       459
weighted avg       0.82      0.79      0.79       459

Successfully trained the model.

In [72]:
import gc
gc.collect()

75

task 39: feature selection using mRMR. We mainly test how many features are optimized for our model by using different number of features to fit the model and compare the model performance.

In [73]:
# !pip install mrmr_selection

In [82]:
from mrmr import mrmr_classif
from sklearn.metrics import accuracy_score, classification_report, matthews_corrcoef
def mrmr_search_feature_number(df, classifier):
    y = df["label"]
    target = "label"
    features = list(df.columns)
    features.remove(target)
    x = df[features]

    # Split data into train and test sets
    X_train, X_test, y_train, y_test = balanced_group_train_test_split(
        x,
        y,
        group_col='augmentated from uniprot ID',
        test_size=0.2,
        random_state=42
    )

    feature_number_lst = [5,10,20,25,30,40,50,100,200]
    for feature_number in feature_number_lst:
        # using mrmr to get the selected features order
        selected_features = mrmr_classif(X=X_train, y=y_train, K=feature_number)
        print(f"selected feature number is {len(selected_features)}")
        print(selected_features)

        X_train_temp = (X_train).copy()[selected_features]
        X_test_temp = X_test.copy()[selected_features]

        trained_model = make_pipeline(classifier)
        trained_model.fit(X_train_temp, y_train)

        # Make predictions
        y_train_pred = trained_model.predict(X_train_temp)
        y_test_pred = trained_model.predict(X_test_temp)

        # Calculate model metrics
        train_accuracy = accuracy_score(y_train, y_train_pred)
        test_accuracy = accuracy_score(y_test, y_test_pred)
        
        train_mcc = matthews_corrcoef(y_train, y_train_pred)
        test_mcc = matthews_corrcoef(y_test, y_test_pred)
        
        train_report = classification_report(y_train, y_train_pred, zero_division=1)
        test_report = classification_report(y_test, y_test_pred, zero_division=1)
        
        # Print metrics in a readable format
        print("Model Performance Metrics:\n")
        
        print("Training Data Metrics:")
        print(f"Accuracy: {train_accuracy:.2f}")
        print(f"MCC: {train_mcc:.2f}")
        print("Classification Report:")
        print(train_report)
        
        print("\nTest Data Metrics:")
        print(f"Accuracy: {test_accuracy:.2f}")
        print(f"MCC: {test_mcc:.2f}")
        print("Classification Report:")
        print(test_report)
        
        print(f"\nSuccessfully trained the model with {len(selected_features)} feature{'s' if len(selected_features) > 1 else ''}.")

In [83]:
# first mrmr selection on the biological features

In [84]:
print("biological features mrmr selection")
mrmr_search_feature_number(biology_training_dataset_df, RandomForestClassifier(max_depth=7))

biological features mrmr selection

100%|██████████| 5/5 [00:00<00:00, 24.27it/s]

selected feature number is 5
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.88
MCC: 0.76
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.87      0.88       966
           1       0.85      0.89      0.87       841

    accuracy                           0.88      1807
   macro avg       0.88      0.88      0.88      1807
weighted avg       0.88      0.88      0.88      1807


Test Data Metrics:
Accuracy: 0.83
MCC: 0.65
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       233
           1       0.84      0.80      0.82       226

    accuracy                           0.83       459
   macro avg       0.83      0.83      0.83       459
weighted avg       0.83      0.83      0.83       459


Successfully trained the model with 5 features.

100%|██████████| 10/10 [00:00<00:00, 29.83it/s]

selected feature number is 10
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.89
MCC: 0.78
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.88      0.90       966
           1       0.87      0.90      0.88       841

    accuracy                           0.89      1807
   macro avg       0.89      0.89      0.89      1807
weighted avg       0.89      0.89      0.89      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       233
           1       0.85      0.82      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 10 features.

100%|██████████| 20/20 [00:00<00:00, 33.07it/s]

selected feature number is 20
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.89
MCC: 0.78
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.89      0.90       966
           1       0.87      0.90      0.88       841

    accuracy                           0.89      1807
   macro avg       0.89      0.89      0.89      1807
weighted avg       0.89      0.89      0.89      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.69
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       233
           1       0.87      0.81      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 20 features.

100%|██████████| 25/25 [00:00<00:00, 32.99it/s]

selected feature number is 25
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s', 'onehot_1_R', 'onehot_-3_G', 'SHD', 'onehot_-3_A', 'onehot_-3_D']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.89
MCC: 0.78
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.88      0.89       966
           1       0.87      0.90      0.88       841

    accuracy                           0.89      1807
   macro avg       0.89      0.89      0.89      1807
weighted avg       0.89      0.89      0.89      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       233
           1       0.86      0.80      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 25 features.

100%|██████████| 30/30 [00:00<00:00, 30.43it/s]

selected feature number is 30
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s', 'onehot_1_R', 'onehot_-3_G', 'SHD', 'onehot_-3_A', 'onehot_-3_D', 'onehot_-5_R', 'onehot_-3_N', 'onehot_-3_P', 'onehot_3_D', 'onehot_-3_L']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.89
MCC: 0.78
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.88      0.90       966
           1       0.87      0.90      0.88       841

    accuracy                           0.89      1807
   macro avg       0.89      0.89      0.89      1807
weighted avg       0.89      0.89      0.89      1807


Test Data Metrics:
Accuracy: 0.85
MCC: 0.70
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       233
           1       0.86      0.84      0.85       226

    accuracy                           0.85       459
   macro avg       0.85      0.85      0.85       459
weighted avg       0.85      0.85      0.85       459


Successfully trained the model with 30 features.

100%|██████████| 40/40 [00:01<00:00, 30.37it/s]

selected feature number is 40
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s', 'onehot_1_R', 'onehot_-3_G', 'SHD', 'onehot_-3_A', 'onehot_-3_D', 'onehot_-5_R', 'onehot_-3_N', 'onehot_-3_P', 'onehot_3_D', 'onehot_-3_L', 'FCR', 'onehot_-3_Q', 'onehot_2_A', 'onehot_4_Q', 'deephase_w2v_multi', 'NCPR', 'onehot_-2_D', 'mean_lambda', 'onehot_1_E', 'onehot_-2_N']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.90
MCC: 0.80
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.89      0.90       966
           1       0.88      0.91      0.89       841

    accuracy                           0.90      1807
   macro avg       0.90      0.90      0.90      1807
weighted avg       0.90      0.90      0.90      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.67
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.87      0.84       233
           1       0.85      0.81      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 40 features.

100%|██████████| 50/50 [00:01<00:00, 29.54it/s]

selected feature number is 50
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s', 'onehot_1_R', 'onehot_-3_G', 'SHD', 'onehot_-3_A', 'onehot_-3_D', 'onehot_-5_R', 'onehot_-3_N', 'onehot_-3_P', 'onehot_3_D', 'onehot_-3_L', 'FCR', 'onehot_-3_Q', 'onehot_2_A', 'onehot_4_Q', 'deephase_w2v_multi', 'NCPR', 'onehot_-2_D', 'mean_lambda', 'onehot_1_E', 'onehot_-2_N', 'onehot_-5_N', 'onehot_-1_G', 'onehot_2_I', 'onehot_1_G', 'onehot_2_F', 'onehot_-1_D', 'SconfSVR/N (kB)', 'onehot_-2_L', 'onehot_7_G', 'onehot_5_H']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.90
MCC: 0.80
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.91       966
           1       0.89      0.90      0.89       841

    accuracy                           0.90      1807
   macro avg       0.90      0.90      0.90      1807
weighted avg       0.90      0.90      0.90      1807


Test Data Metrics:
Accuracy: 0.83
MCC: 0.65
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       233
           1       0.84      0.80      0.82       226

    accuracy                           0.83       459
   macro avg       0.83      0.83      0.83       459
weighted avg       0.83      0.83      0.83       459


Successfully trained the model with 50 features.

100%|██████████| 100/100 [00:03<00:00, 28.09it/s]

selected feature number is 100
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s', 'onehot_1_R', 'onehot_-3_G', 'SHD', 'onehot_-3_A', 'onehot_-3_D', 'onehot_-5_R', 'onehot_-3_N', 'onehot_-3_P', 'onehot_3_D', 'onehot_-3_L', 'FCR', 'onehot_-3_Q', 'onehot_2_A', 'onehot_4_Q', 'deephase_w2v_multi', 'NCPR', 'onehot_-2_D', 'mean_lambda', 'onehot_1_E', 'onehot_-2_N', 'onehot_-5_N', 'onehot_-1_G', 'onehot_2_I', 'onehot_1_G', 'onehot_2_F', 'onehot_-1_D', 'SconfSVR/N (kB)', 'onehot_-2_L', 'onehot_7_G', 'onehot_5_H', 'onehot_-1_N', 'onehot_1_A', 'onehot_-2_E', 'nuSVR', 'onehot_-4_K', 'onehot_-5_T', 'deephase_score', 'onehot_2_L', 'onehot_-2_F', 'onehot_-3_W', 'onehot_-6_G', 'onehot_-2_V', 'onehot_7_W', 'onehot_-1_E', 'onehot_3_R', 'onehot_-2_P', 'onehot_-4_G', 'onehot_1_H', 'fK', 'onehot_-1_M', 'onehot_6_Q', 'onehot_-2_M', 'onehot_-3_T', 'onehot_1_S', 'onehot_-7_P', 'kappa', 'onehot_3_W', 'onehot_-6_V', 'onehot_-6_R', 'onehot_-3_M', 'onehot_5_A', 'onehot_-3_C', 'onehot_-5_A', 'onehot_-6_M', 'onehot_-3_I', 'onehot_6_S', 'onehot_-5_D', 'onehot_-2_K', 'onehot_2_C', 'onehot_-7_C', 'onehot_4_H', 'fD', 'onehot_-6_D', 'onehot_-7_S', 'onehot_-7_E', 'faro', 'onehot_-3_F', 'onehot_2_R', 'onehot_1_I', 'onehot_-6_Q']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.90
MCC: 0.80
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.91       966
           1       0.89      0.90      0.90       841

    accuracy                           0.90      1807
   macro avg       0.90      0.90      0.90      1807
weighted avg       0.90      0.90      0.90      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.85       233
           1       0.85      0.82      0.84       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 100 features.

100%|██████████| 200/200 [00:06<00:00, 31.81it/s]

selected feature number is 200
['onehot_-3_R', 'onehot_-1_K', 'onehot_2_P', 'phospho_score', 'onehot_-2_S', 'onehot_1_L', 'onehot_0_t', 'onehot_-3_E', 'fR', 'onehot_1_P', 'onehot_4_L', 'onehot_-3_S', 'onehot_-4_R', 'iupred_score', 'onehot_-2_G', 'onehot_-3_V', 'onehot_2_K', 'onehot_-2_R', 'onehot_-1_H', 'onehot_0_s', 'onehot_1_R', 'onehot_-3_G', 'SHD', 'onehot_-3_A', 'onehot_-3_D', 'onehot_-5_R', 'onehot_-3_N', 'onehot_-3_P', 'onehot_3_D', 'onehot_-3_L', 'FCR', 'onehot_-3_Q', 'onehot_2_A', 'onehot_4_Q', 'deephase_w2v_multi', 'NCPR', 'onehot_-2_D', 'mean_lambda', 'onehot_1_E', 'onehot_-2_N', 'onehot_-5_N', 'onehot_-1_G', 'onehot_2_I', 'onehot_1_G', 'onehot_2_F', 'onehot_-1_D', 'SconfSVR/N (kB)', 'onehot_-2_L', 'onehot_7_G', 'onehot_5_H', 'onehot_-1_N', 'onehot_1_A', 'onehot_-2_E', 'nuSVR', 'onehot_-4_K', 'onehot_-5_T', 'deephase_score', 'onehot_2_L', 'onehot_-2_F', 'onehot_-3_W', 'onehot_-6_G', 'onehot_-2_V', 'onehot_7_W', 'onehot_-1_E', 'onehot_3_R', 'onehot_-2_P', 'onehot_-4_G', 'onehot_1_H', 'fK', 'onehot_-1_M', 'onehot_6_Q', 'onehot_-2_M', 'onehot_-3_T', 'onehot_1_S', 'onehot_-7_P', 'kappa', 'onehot_3_W', 'onehot_-6_V', 'onehot_-6_R', 'onehot_-3_M', 'onehot_5_A', 'onehot_-3_C', 'onehot_-5_A', 'onehot_-6_M', 'onehot_-3_I', 'onehot_6_S', 'onehot_-5_D', 'onehot_-2_K', 'onehot_2_C', 'onehot_-7_C', 'onehot_4_H', 'fD', 'onehot_-6_D', 'onehot_-7_S', 'onehot_-7_E', 'faro', 'onehot_-3_F', 'onehot_2_R', 'onehot_1_I', 'onehot_-6_Q', 'onehot_5_P', 'fE', 'onehot_-7_D', 'onehot_6_P', 'onehot_-4_I', 'onehot_-5_L', 'onehot_6_I', 'onehot_2_Y', 'onehot_2_Q', 'onehot_6_A', 'onehot_-7_H', 'onehot_-2_A', 'onehot_-2_I', 'onehot_-6_S', 'onehot_2_W', 'onehot_5_Q', 'onehot_-2_s', 'onehot_-6_F', 'onehot_-7_I', 'onehot_7_N', 'onehot_-6_K', 'onehot_7_T', 'onehot_2_E', 'onehot_5_R', 'onehot_2_M', 'onehot_5_T', 'onehot_5_G', 'onehot_-7_G', 'onehot_-5_S', 'onehot_1_K', 'onehot_4_S', 'onehot_-1_L', 'onehot_2_N', 'onehot_-7_V', 'onehot_4_K', 'onehot_1_C', 'onehot_1_W', 'onehot_3_V', 'onehot_-2_Y', 'onehot_5_I', 'onehot_6_Y', 'onehot_1_F', 'onehot_3_A', 'onehot_-3_H', 'onehot_-5_Q', 'onehot_-4_C', 'onehot_5_Y', 'onehot_-5_M', 'onehot_-4_Y', 'onehot_-1_I', 'onehot_-6_A', 'onehot_2_V', 'onehot_-4_P', 'onehot_5_V', 'onehot_-6_Y', 'onehot_-1_A', 'onehot_4_A', 'onehot_7_Y', 'onehot_-1_Y', 'onehot_-6_W', 'onehot_-5_W', 'onehot_1_M', 'onehot_-5_I', 'onehot_4_W', 'onehot_-6_P', 'onehot_7_P', 'onehot_-6_C', 'onehot_6_K', 'onehot_7_S', 'onehot_1_N', 'onehot_1_Q', 'onehot_-4_A', 'onehot_-5_E', 'onehot_3_M', 'onehot_-7_Y', 'onehot_7_I', 'onehot_-7_F', 'onehot_-1_C', 'onehot_-4_D', 'onehot_7_M', 'onehot_3_K', 'SCD', 'onehot_2_t', 'onehot_6_V', 'onehot_-1_T', 'onehot_-7_R', 'onehot_-4_N', 'deephase_phys_multi', 'onehot_1_Y', 'onehot_4_I', 'onehot_-6_E', 'onehot_-7_A', 'onehot_5_E', 'onehot_-4_E', 'onehot_4_P', 'onehot_1_D', 'onehot_-4_V', 'onehot_4_C', 'onehot_3_I', 'onehot_6_D']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.90
MCC: 0.80
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.91       966
           1       0.89      0.90      0.89       841

    accuracy                           0.90      1807
   macro avg       0.90      0.90      0.90      1807
weighted avg       0.90      0.90      0.90      1807


Test Data Metrics:
Accuracy: 0.83
MCC: 0.67
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       233
           1       0.84      0.81      0.83       226

    accuracy                           0.83       459
   macro avg       0.83      0.83      0.83       459
weighted avg       0.83      0.83      0.83       459


Successfully trained the model with 200 features.

In [85]:
# then mrmr selection on all the features

In [86]:
training_dataset_df = pd.read_pickle("final_dataset_with_all_new.pkl")
training_dataset_df = training_dataset_df[training_dataset_df["usage"] == "training"]
columns_to_keep = [col for col in training_dataset_df.columns if col not in always_exclude_columns]
training_dataset_df[columns_to_keep]

,label,augmentated from uniprot ID,deephase_phys_multi,deephase_w2v_multi,deephase_score,iupred_score,onehot_-7_A,onehot_-7_C,onehot_-7_D,onehot_-7_E,...,ptmmamba_residue_embedding_759,ptmmamba_residue_embedding_760,ptmmamba_residue_embedding_761,ptmmamba_residue_embedding_762,ptmmamba_residue_embedding_763,ptmmamba_residue_embedding_764,ptmmamba_residue_embedding_765,ptmmamba_residue_embedding_766,ptmmamba_residue_embedding_767,phospho_score
0,1,P16333,0.203,0.160,0.182,0.541878,0.0,0.0,0.0,0.0,...,-0.930157,-0.784488,1.378070,1.125187,-0.962103,0.749272,-0.813084,0.488083,1.446624,0.526
1,1,P16333,0.185,0.173,0.179,0.509769,0.0,0.0,0.0,0.0,...,-0.833150,-0.543848,1.270835,1.192153,-0.817320,0.709415,-1.378276,0.626975,2.133350,0.579
2,1,P16333,0.096,0.129,0.113,0.465241,0.0,0.0,0.0,0.0,...,-1.474621,-0.104392,1.062815,0.442375,-0.308503,-0.050680,-1.171706,1.861005,0.189925,0.571
3,1,P16333,0.108,0.352,0.230,0.566480,0.0,0.0,0.0,0.0,...,-0.708835,-0.368524,0.630111,0.287115,0.439652,0.259266,-1.870489,2.179887,0.830376,0.379
4,1,Q5VWQ8,0.282,0.742,0.512,0.837511,0.0,0.0,0.0,0.0,...,-0.940106,-0.094523,0.474609,-0.267281,-0.266375,0.243640,-0.773728,1.224039,-0.136662,0.374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2261,0,O15417,0.329,0.774,0.552,0.798249,0.0,0.0,0.0,0.0,...,-1.177676,-0.877304,0.674698,-0.195342,0.283925,0.078973,0.930381,0.637896,-0.366109,0.080
2262,0,Q9BYW2,0.283,0.776,0.530,0.831250,0.0,0.0,0.0,0.0,...,-1.549038,-0.295345,-0.262526,-0.634858,-0.357382,0.593850,-0.580129,0.019379,-0.784574,0.274
2263,0,Q8N3K9,0.203,0.726,0.464,0.566480,0.0,0.0,0.0,0.0,...,-0.909634,-0.845351,-0.325931,-0.011938,-0.855250,-0.535025,0.514734,0.020328,-0.189157,0.063
2264,0,Q6ZRS2,0.411,0.762,0.587,0.930790,0.0,0.0,0.0,0.0,...,-1.190711,0.183619,1.008728,-0.325716,-1.453191,-0.757268,-0.204297,0.862000,-1.027532,0.155
2265,0,Q12955,0.275,0.749,0.512,0.915074,0.0,0.0,0.0,1.0,...,-0.947864,0.082668,-0.058106,-1.147494,-0.545297,-0.056368,-0.360111,0.239430,-1.013324,0.118

In [87]:
mrmr_search_feature_number(training_dataset_df[columns_to_keep], RandomForestClassifier(max_depth=7))

100%|██████████| 5/5 [00:01<00:00,  3.78it/s]

selected feature number is 5
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.89
MCC: 0.78
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.87      0.89       966
           1       0.86      0.90      0.88       841

    accuracy                           0.89      1807
   macro avg       0.89      0.89      0.89      1807
weighted avg       0.89      0.89      0.89      1807


Test Data Metrics:
Accuracy: 0.83
MCC: 0.66
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.84      0.84       233
           1       0.83      0.82      0.83       226

    accuracy                           0.83       459
   macro avg       0.83      0.83      0.83       459
weighted avg       0.83      0.83      0.83       459


Successfully trained the model with 5 features.

100%|██████████| 10/10 [00:02<00:00,  3.34it/s]

selected feature number is 10
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.92
MCC: 0.84
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.91      0.92       966
           1       0.90      0.93      0.91       841

    accuracy                           0.92      1807
   macro avg       0.92      0.92      0.92      1807
weighted avg       0.92      0.92      0.92      1807


Test Data Metrics:
Accuracy: 0.86
MCC: 0.71
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86       233
           1       0.86      0.85      0.85       226

    accuracy                           0.86       459
   macro avg       0.86      0.86      0.86       459
weighted avg       0.86      0.86      0.86       459


Successfully trained the model with 10 features.

100%|██████████| 20/20 [00:06<00:00,  3.14it/s]

selected feature number is 20
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.93
MCC: 0.85
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       966
           1       0.91      0.93      0.92       841

    accuracy                           0.93      1807
   macro avg       0.93      0.93      0.93      1807
weighted avg       0.93      0.93      0.93      1807


Test Data Metrics:
Accuracy: 0.86
MCC: 0.71
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.87      0.86       233
           1       0.86      0.85      0.85       226

    accuracy                           0.86       459
   macro avg       0.86      0.86      0.86       459
weighted avg       0.86      0.86      0.86       459


Successfully trained the model with 20 features.

100%|██████████| 25/25 [00:07<00:00,  3.13it/s]

selected feature number is 25
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453', 'esm_protein_embedding_68', 'esm_residue_embedding_1242', 'esm_residue_embedding_482', 'esm_residue_embedding_844', 'esm_residue_embedding_1074']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.93
MCC: 0.86
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.93      0.94       966
           1       0.92      0.93      0.93       841

    accuracy                           0.93      1807
   macro avg       0.93      0.93      0.93      1807
weighted avg       0.93      0.93      0.93      1807


Test Data Metrics:
Accuracy: 0.86
MCC: 0.73
Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       233
           1       0.89      0.83      0.86       226

    accuracy                           0.86       459
   macro avg       0.86      0.86      0.86       459
weighted avg       0.86      0.86      0.86       459


Successfully trained the model with 25 features.

100%|██████████| 30/30 [00:09<00:00,  3.01it/s]

selected feature number is 30
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453', 'esm_protein_embedding_68', 'esm_residue_embedding_1242', 'esm_residue_embedding_482', 'esm_residue_embedding_844', 'esm_residue_embedding_1074', 'esm_residue_embedding_1042', 'esm_residue_embedding_333', 'esm_residue_embedding_692', 'esm_residue_embedding_313', 'esm_residue_embedding_960']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.93
MCC: 0.86
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.93      0.94       966
           1       0.92      0.93      0.93       841

    accuracy                           0.93      1807
   macro avg       0.93      0.93      0.93      1807
weighted avg       0.93      0.93      0.93      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       233
           1       0.88      0.79      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 30 features.

100%|██████████| 40/40 [00:13<00:00,  2.94it/s]

selected feature number is 40
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453', 'esm_protein_embedding_68', 'esm_residue_embedding_1242', 'esm_residue_embedding_482', 'esm_residue_embedding_844', 'esm_residue_embedding_1074', 'esm_residue_embedding_1042', 'esm_residue_embedding_333', 'esm_residue_embedding_692', 'esm_residue_embedding_313', 'esm_residue_embedding_960', 'esm_residue_embedding_2', 'esm_residue_embedding_291', 'esm_residue_embedding_650', 'esm_residue_embedding_1110', 'esm_residue_embedding_75', 'esm_residue_embedding_466', 'esm_residue_embedding_206', 'esm_residue_embedding_944', 'esm_residue_embedding_235', 'esm_residue_embedding_245']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.93
MCC: 0.87
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.93      0.94       966
           1       0.93      0.93      0.93       841

    accuracy                           0.93      1807
   macro avg       0.93      0.93      0.93      1807
weighted avg       0.93      0.93      0.93      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       233
           1       0.88      0.78      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 40 features.

100%|██████████| 50/50 [00:16<00:00,  2.97it/s]

selected feature number is 50
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453', 'esm_protein_embedding_68', 'esm_residue_embedding_1242', 'esm_residue_embedding_482', 'esm_residue_embedding_844', 'esm_residue_embedding_1074', 'esm_residue_embedding_1042', 'esm_residue_embedding_333', 'esm_residue_embedding_692', 'esm_residue_embedding_313', 'esm_residue_embedding_960', 'esm_residue_embedding_2', 'esm_residue_embedding_291', 'esm_residue_embedding_650', 'esm_residue_embedding_1110', 'esm_residue_embedding_75', 'esm_residue_embedding_466', 'esm_residue_embedding_206', 'esm_residue_embedding_944', 'esm_residue_embedding_235', 'esm_residue_embedding_245', 'esm_residue_embedding_447', 'esm_residue_embedding_1250', 'esm_residue_embedding_1012', 'esm_residue_embedding_861', 'esm_residue_embedding_293', 'esm_residue_embedding_217', 'esm_residue_embedding_278', 'esm_residue_embedding_989', 'esm_residue_embedding_48', 'esm_residue_embedding_300']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.94
MCC: 0.88
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.94      0.94       966
           1       0.93      0.94      0.93       841

    accuracy                           0.94      1807
   macro avg       0.94      0.94      0.94      1807
weighted avg       0.94      0.94      0.94      1807


Test Data Metrics:
Accuracy: 0.84
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.90      0.85       233
           1       0.88      0.77      0.83       226

    accuracy                           0.84       459
   macro avg       0.84      0.84      0.84       459
weighted avg       0.84      0.84      0.84       459


Successfully trained the model with 50 features.

100%|██████████| 100/100 [00:34<00:00,  2.94it/s]

selected feature number is 100
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453', 'esm_protein_embedding_68', 'esm_residue_embedding_1242', 'esm_residue_embedding_482', 'esm_residue_embedding_844', 'esm_residue_embedding_1074', 'esm_residue_embedding_1042', 'esm_residue_embedding_333', 'esm_residue_embedding_692', 'esm_residue_embedding_313', 'esm_residue_embedding_960', 'esm_residue_embedding_2', 'esm_residue_embedding_291', 'esm_residue_embedding_650', 'esm_residue_embedding_1110', 'esm_residue_embedding_75', 'esm_residue_embedding_466', 'esm_residue_embedding_206', 'esm_residue_embedding_944', 'esm_residue_embedding_235', 'esm_residue_embedding_245', 'esm_residue_embedding_447', 'esm_residue_embedding_1250', 'esm_residue_embedding_1012', 'esm_residue_embedding_861', 'esm_residue_embedding_293', 'esm_residue_embedding_217', 'esm_residue_embedding_278', 'esm_residue_embedding_989', 'esm_residue_embedding_48', 'esm_residue_embedding_300', 'esm_residue_embedding_355', 'esm_residue_embedding_1207', 'esm_residue_embedding_622', 'esm_residue_embedding_1142', 'esm_residue_embedding_440', 'esm_residue_embedding_1000', 'esm_residue_embedding_290', 'esm_residue_embedding_107', 'esm_residue_embedding_122', 'esm_residue_embedding_325', 'esm_protein_embedding_817', 'esm_protein_embedding_850', 'esm_residue_embedding_12', 'esm_residue_embedding_703', 'esm_residue_embedding_669', 'esm_residue_embedding_50', 'esm_residue_embedding_1109', 'esm_residue_embedding_304', 'esm_residue_embedding_1131', 'esm_residue_embedding_1198', 'esm_residue_embedding_1164', 'onehot_-2_S', 'esm_residue_embedding_205', 'ptmmamba_residue_embedding_257', 'esm_residue_embedding_1038', 'esm_residue_embedding_282', 'esm_residue_embedding_1170', 'esm_residue_embedding_766', 'esm_residue_embedding_965', 'esm_residue_embedding_995', 'esm_residue_embedding_1006', 'esm_residue_embedding_450', 'esm_residue_embedding_843', 'esm_residue_embedding_1264', 'esm_residue_embedding_253', 'esm_residue_embedding_78', 'esm_residue_embedding_179', 'esm_residue_embedding_939', 'esm_residue_embedding_707', 'esm_residue_embedding_825', 'esm_residue_embedding_269', 'esm_residue_embedding_676', 'esm_residue_embedding_199', 'esm_residue_embedding_181', 'esm_residue_embedding_44', 'esm_residue_embedding_344', 'esm_residue_embedding_1176', 'esm_residue_embedding_792', 'esm_residue_embedding_1134', 'esm_residue_embedding_5']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.95
MCC: 0.90
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       966
           1       0.95      0.94      0.94       841

    accuracy                           0.95      1807
   macro avg       0.95      0.95      0.95      1807
weighted avg       0.95      0.95      0.95      1807


Test Data Metrics:
Accuracy: 0.83
MCC: 0.68
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.91      0.85       233
           1       0.89      0.75      0.82       226

    accuracy                           0.83       459
   macro avg       0.84      0.83      0.83       459
weighted avg       0.84      0.83      0.83       459


Successfully trained the model with 100 features.

100%|██████████| 200/200 [01:07<00:00,  2.96it/s]

selected feature number is 200
['onehot_-3_R', 'ptmmamba_residue_embedding_79', 'ptmmamba_residue_embedding_408', 'esm_residue_embedding_81', 'onehot_2_P', 'esm_residue_embedding_1041', 'esm_residue_embedding_715', 'esm_residue_embedding_1171', 'phospho_score', 'esm_residue_embedding_491', 'esm_residue_embedding_1259', 'esm_residue_embedding_394', 'esm_residue_embedding_1215', 'esm_residue_embedding_53', 'esm_residue_embedding_546', 'esm_residue_embedding_356', 'esm_residue_embedding_197', 'esm_residue_embedding_327', 'esm_residue_embedding_385', 'esm_residue_embedding_453', 'esm_protein_embedding_68', 'esm_residue_embedding_1242', 'esm_residue_embedding_482', 'esm_residue_embedding_844', 'esm_residue_embedding_1074', 'esm_residue_embedding_1042', 'esm_residue_embedding_333', 'esm_residue_embedding_692', 'esm_residue_embedding_313', 'esm_residue_embedding_960', 'esm_residue_embedding_2', 'esm_residue_embedding_291', 'esm_residue_embedding_650', 'esm_residue_embedding_1110', 'esm_residue_embedding_75', 'esm_residue_embedding_466', 'esm_residue_embedding_206', 'esm_residue_embedding_944', 'esm_residue_embedding_235', 'esm_residue_embedding_245', 'esm_residue_embedding_447', 'esm_residue_embedding_1250', 'esm_residue_embedding_1012', 'esm_residue_embedding_861', 'esm_residue_embedding_293', 'esm_residue_embedding_217', 'esm_residue_embedding_278', 'esm_residue_embedding_989', 'esm_residue_embedding_48', 'esm_residue_embedding_300', 'esm_residue_embedding_355', 'esm_residue_embedding_1207', 'esm_residue_embedding_622', 'esm_residue_embedding_1142', 'esm_residue_embedding_440', 'esm_residue_embedding_1000', 'esm_residue_embedding_290', 'esm_residue_embedding_107', 'esm_residue_embedding_122', 'esm_residue_embedding_325', 'esm_protein_embedding_817', 'esm_protein_embedding_850', 'esm_residue_embedding_12', 'esm_residue_embedding_703', 'esm_residue_embedding_669', 'esm_residue_embedding_50', 'esm_residue_embedding_1109', 'esm_residue_embedding_304', 'esm_residue_embedding_1131', 'esm_residue_embedding_1198', 'esm_residue_embedding_1164', 'onehot_-2_S', 'esm_residue_embedding_205', 'ptmmamba_residue_embedding_257', 'esm_residue_embedding_1038', 'esm_residue_embedding_282', 'esm_residue_embedding_1170', 'esm_residue_embedding_766', 'esm_residue_embedding_965', 'esm_residue_embedding_995', 'esm_residue_embedding_1006', 'esm_residue_embedding_450', 'esm_residue_embedding_843', 'esm_residue_embedding_1264', 'esm_residue_embedding_253', 'esm_residue_embedding_78', 'esm_residue_embedding_179', 'esm_residue_embedding_939', 'esm_residue_embedding_707', 'esm_residue_embedding_825', 'esm_residue_embedding_269', 'esm_residue_embedding_676', 'esm_residue_embedding_199', 'esm_residue_embedding_181', 'esm_residue_embedding_44', 'esm_residue_embedding_344', 'esm_residue_embedding_1176', 'esm_residue_embedding_792', 'esm_residue_embedding_1134', 'esm_residue_embedding_5', 'esm_residue_embedding_754', 'esm_residue_embedding_1024', 'esm_residue_embedding_384', 'esm_protein_embedding_137', 'esm_residue_embedding_685', 'esm_residue_embedding_462', 'esm_residue_embedding_1047', 'esm_residue_embedding_200', 'esm_residue_embedding_609', 'esm_residue_embedding_127', 'esm_residue_embedding_871', 'esm_residue_embedding_636', 'esm_residue_embedding_693', 'esm_residue_embedding_195', 'esm_residue_embedding_771', 'esm_residue_embedding_1205', 'esm_residue_embedding_432', 'esm_residue_embedding_1208', 'esm_residue_embedding_337', 'esm_protein_embedding_756', 'esm_residue_embedding_1096', 'esm_residue_embedding_992', 'esm_residue_embedding_1051', 'esm_residue_embedding_1125', 'esm_residue_embedding_621', 'esm_residue_embedding_114', 'esm_residue_embedding_1211', 'esm_residue_embedding_1255', 'esm_residue_embedding_95', 'onehot_1_P', 'esm_protein_embedding_86', 'esm_residue_embedding_349', 'esm_residue_embedding_860', 'ptmmamba_residue_embedding_190', 'esm_residue_embedding_836', 'esm_residue_embedding_1228', 'esm_residue_embedding_315', 'esm_residue_embedding_765', 'esm_residue_embedding_272', 'esm_residue_embedding_552', 'esm_residue_embedding_757', 'esm_residue_embedding_951', 'esm_residue_embedding_1060', 'esm_residue_embedding_743', 'esm_residue_embedding_614', 'esm_residue_embedding_47', 'esm_residue_embedding_957', 'onehot_-3_E', 'esm_residue_embedding_66', 'esm_residue_embedding_905', 'esm_residue_embedding_1030', 'esm_residue_embedding_850', 'esm_protein_embedding_554', 'esm_residue_embedding_688', 'esm_residue_embedding_196', 'esm_residue_embedding_29', 'esm_residue_embedding_807', 'esm_residue_embedding_985', 'esm_residue_embedding_725', 'onehot_-3_S', 'esm_residue_embedding_221', 'esm_residue_embedding_366', 'esm_residue_embedding_88', 'esm_residue_embedding_722', 'esm_residue_embedding_548', 'esm_residue_embedding_585', 'esm_protein_embedding_576', 'esm_residue_embedding_943', 'esm_residue_embedding_1137', 'esm_residue_embedding_257', 'esm_residue_embedding_635', 'esm_residue_embedding_468', 'ptmmamba_residue_embedding_463', 'esm_residue_embedding_459', 'esm_protein_embedding_736', 'esm_residue_embedding_888', 'esm_residue_embedding_498', 'esm_residue_embedding_907', 'esm_residue_embedding_793', 'esm_residue_embedding_1189', 'esm_residue_embedding_175', 'esm_residue_embedding_658', 'esm_residue_embedding_927', 'esm_residue_embedding_417', 'esm_residue_embedding_988', 'esm_residue_embedding_182', 'esm_residue_embedding_110', 'esm_residue_embedding_248', 'esm_residue_embedding_431', 'esm_residue_embedding_727', 'esm_residue_embedding_1186', 'esm_residue_embedding_806', 'esm_residue_embedding_950', 'esm_residue_embedding_45', 'esm_residue_embedding_227', 'esm_residue_embedding_378', 'esm_residue_embedding_232', 'esm_residue_embedding_251', 'esm_residue_embedding_374', 'esm_residue_embedding_1129']
Model Performance Metrics:

Training Data Metrics:
Accuracy: 0.95
MCC: 0.90
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       966
           1       0.94      0.94      0.94       841

    accuracy                           0.95      1807
   macro avg       0.95      0.95      0.95      1807
weighted avg       0.95      0.95      0.95      1807


Test Data Metrics:
Accuracy: 0.82
MCC: 0.65
Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.92      0.84       233
           1       0.90      0.71      0.80       226

    accuracy                           0.82       459
   macro avg       0.83      0.82      0.82       459
weighted avg       0.83      0.82      0.82       459


Successfully trained the model with 200 features.

task 40: We also test feature selection using another method Boruta, it shows that XX feature give us the best results.

In [ ]:
# initial parameters
def boruta_feature_selection(df, classifier)
    y = df["label"]
    target = "label"
    features = list(df.columns)
    features.remove(target)
    x = df[features]

    # Split data into train and test sets
    x_train, x_test, y_train, y_test = train_test_split(
        x,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )


    alpha = 0.01
    perc = 100
    max_iter = 80

    features = X_train.columns
    tree_model = classifier
    X_train_temp = X_train.copy()

    # Boruta search
    feat_selector = BorutaPy(tree_model, 
                             n_estimators='auto', 
                             verbose=2, 
                             random_state=0, 
                             perc = perc, 
                             max_iter = max_iter, 
                             alpha = alpha)

    feat_selector.fit(X_train_temp, y_train)

    # get the feature that will be deleted
    rank_mask = feat_selector.ranking_
    deleted_features = [X_train_temp.columns[i] for i, num in enumerate(rank_mask) if (num != 2 and num !=1)]

    # Convert the result set to a string
    result_str = ', '.join(map(str, set(features)-set(deleted_features)))

    # Open a file in write mode and save the result
    with open('20240517 boruta selected features.txt', 'w') as file:
        file.write(result_str)

    # if I want to control the number of feature to selected
    remaining_feature_number = len(X_train.columns) - len(deleted_features)
    print("remaining feature number: ", remaining_feature_number)
    print("remaining feature", set(features)-set(deleted_features))
    return set(features)-set(deleted_features)

In [ ]:
selected_features = boruta_feature_selection(training_dataset_df)

task 41: feature importance and its contribution were
further analyzed to find which feature was more valuable for
the model performance after feature selection

In [ ]:
# Prefixes for PLM features
plm_prefixes = (
    'esm_protein_embedding_position',
    'esm_residue_embedding_position',
    'ptmmamba_residue_embedding_position',
    'ptmmamba_protein_embedding_position'
)

# Identify PLM and Biological features
plm_features = [feature for feature in selected_features if feature.startswith(plm_prefixes)]
bio_features = [feature for feature in selected_features if not feature.startswith(plm_prefixes)]

# Counts
plm_count = len(plm_features)
bio_count = len(bio_features)

# Output
print(f"PLM features ({plm_count}): {plm_features}")
print(f"Biological features ({bio_count}): {bio_features}")

print(f"PLM features: {plm_count}")
print(f"Biological features: {bio_count}")

### 4.4	Prediction performance with different classifiers

task 42: To test the validity of the optimal feature set in different classifiers, three common classifiers were used to predict 14-3-3 sites: random forest (RF), XGBoost (XGB), SVM and ANN are used.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

classifer_lst = [RandomForestClassifier(), XGBClassifier(), SVC(), MLPClassifier()]

for classifer in classifer_lst:
    train(df, classifier)

## 4.5	Model architecture and optimization

task 43: fine-tuned certain hyperparameters (Table X) of the model

In [ ]:
y = df["label"]
target = "label"
features = list(df.columns)
features.remove(target)
x = df[features]

# Split data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

steps = [('classifier', XGBClassifier())]
pipe = Pipeline(steps)

In [ ]:
parameters = {
    'classifier__n_estimators': [100, 200, 300],
    'classifier__learning_rate': [0.01, 0.05, 0.1],
    'classifier__max_depth': [2,3,4],
    'classifier__gamma': [0, 0.5, 1],
    'classifier__reg_alpha': [0, 0.5, 1],
    'classifier__reg_lambda': [0.5, 1, 5],
    'classifier__base_score': [0.2, 0.5, 1]
}

In [ ]:
scorer = make_scorer(average_precision_score)
model_gsv = GridSearchCV(pipe, parameters, cv = 5, scoring = scorer, n_jobs=-1, verbose=0)
model_gsv = model_gsv.fit(X_train, y_train)
model_gsv.best_params_
best_xgboost_model = model_gsv.best_estimator_

In [ ]:
model_gsv.best_params_

In [ ]:
# Evaluate the best model on the test set
y_train_proba = best_xgboost_model.predict_proba(X_train)[:, 1]
y_train_pred = best_xgboost_model.predict(X_train)
    
model_classification_report = classification_report(y_train, y_train_pred)
    
y_valid_proba = best_xgboost_model.predict_proba(X_valid)[:, 1]
y_valid_pred = best_xgboost_model.predict(X_valid)    
    
model_classification_report_valid = classification_report(y_valid, y_valid_pred)

print("XGBoost Model")
print("Training performance:")
print(f"average_precision_score: {average_precision_score(y_train, y_train_proba):.3e}")
print(f"model_classification_report of traning data:")
print(model_classification_report)
print("-" * 20)
print("Testing performance:")
print(f"average_precision_score: {average_precision_score(y_valid, y_valid_proba):.3e}")
print(f"model_classification_report of valida data:")
print(model_classification_report_valid)
print("-" * 20)

## 4.6 Feature Importance analysis

task 44: we conducted a thorough examination of feature importance using SHAP (SHapley Additive exPlanations) values

In [ ]:
best_model = best_xgboost_model

In [ ]:
select_feature_instance = best_model.named_steps['Drop']

# Accessing the mi_select_cols attribute
feature_names = select_feature_instance.select_cols

feature_importances = best_model.named_steps['classifier'].feature_importances_

# Print or use mi_select_cols as needed
print("Selected features: ", feature_names)

feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
feature_importance_df[:20]

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Sorting the DataFrame based on the 'Value' column in descending order
df_sorted = feature_importance_df.sort_values(by='Importance', ascending=True)

# Plotting the data
plt.figure(figsize=(10, 6))  # Set the figure size
plt.barh(df_sorted.iloc[:, 0], df_sorted.iloc[:, 1], color='skyblue')  # Create a horizontal bar plot

# Adding title and labels
plt.title('Feature vs Importance')
plt.ylabel(df_sorted.columns[0])
plt.xlabel(df_sorted.columns[1])

# Display the plot
plt.show()

In [ ]:
# !pip install shap
import shap

random_forest_model = best_model.named_steps['classifier']
# print(type(random_forest_model))
# Create a SHAP explainer

# Create a SHAP explainer
explainer = shap.TreeExplainer(random_forest_model)

# Calculate SHAP values
shap_values = explainer(df_drop[feature_names])


# Visualize feature importance with feature values
shap.plots.beeswarm(shap_values, show=True)

task 45: ablation experiments where we systematically removed features to observe changes in model performance.

## 4.7	Performance evaluation and comparison with existing methods, Validation on independent test sets

task 46: Independent datset test with 14-3-3 pred and 14-3-3 site-finder, compare with our results.